## Mean:

In [35]:
import numpy as np

def mymean(data):
    sum = 0

    for i in data:
        sum = sum + i

    return sum/len(data)

if __name__ == "__main__":
    data = np.array([int(i) for i in input("Enter the Data: ").split()])
    print(data)

    print(f"Mean of the given data: {mymean(data)}")

Enter the Data: 1 2 3 4 5 6 7 8 9
[1 2 3 4 5 6 7 8 9]
Mean of the given data: 5.0


## Median:

In [49]:
import numpy as np

def mysort(data):
    n = len(data)
    
    for i in range(n):
        for j in range(n-i-1):
            if data[j]>data[j+1]:
                data[j],data[j+1] = data[j+1],data[j]

def mymedian(data):
    mysort(data)
    
    n = len(data)
    
    if n%2 == 1:
        return data[n//2]
    else:
        return (data[n//2] + data[n//2 - 1])/2

if __name__ == "__main__":
    data = np.array([int(i) for i in input("Enter the Data: ").split()])
    print(data)
    
    print(f"Mean of the given data: {mymedian(data)}")

Enter the Data: 1 2 3 6 9 8 7 4
[1 2 3 6 9 8 7 4]
Mean of the given data: 5.0


## Mode:

In [53]:
import numpy as np

def deldups(data):
    newdata = []
    
    for i in data:
        if i not in newdata:
            newdata.append(i)
    return newdata

def mymode(data):
    newdata = deldups(data)
    
    Maxcount = 0
    Maxindex = 0

    for i in newdata:
        count = 0

        for j in range(len(data)):
            if data[j] == i:
                count = count + 1
            
            if(Maxcount < count):
                Maxcount = count
                Maxindex = i-1
    return data[Maxindex]

if __name__ == "__main__":
    data = np.array([int(i) for i in input("Enter the Data: ").split()])
    print(data)
    
    print(f"Mean of the given data: {mymode(data)}")

Enter the Data: 1 2 3 4 5 6 1 2 3 1
[1 2 3 4 5 6 1 2 3 1]
Mean of the given data: 1
