# Numpy Library

In [11]:
import numpy as np

a = [1,2,3,4]
print(a)

[1, 2, 3, 4]


### array() method:
- Syntax:
- numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0) 

In [12]:
a = np.array(a)
print(a)

[1 2 3 4]


### arange() method:
- Syntax:
- numpy.arrange(start, stop, step, dtype)  

In [15]:
a = np.arange(0,10,2)
print(a)

[0 2 4 6 8]


### empty() method:
- Syntax:
- numpy.empty(shape, dtype=float, order='C', *, like=None)

In [33]:
a = np.empty(6)
print(a)

[2.12199579e-314 2.12199579e-314 2.12199579e-314 2.12199579e-314
 2.12199579e-314 2.12199579e-314]


### zeros() method:
- Syntax:
- numpy.zeros(shape, dtype=float, order='C')

In [16]:
a = np.zeros([3,3],dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


### ones() method:
- Syntax:
- numpy.ones(shape, dtype=None, order='C', *, like=None)

In [17]:
a = np.ones([3,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


### eye() method:
- Syntax:
- numpy.matlib.eye(n, m, k, dtype)

In [18]:
a = np.eye(3,3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### full() method:
- Syntax:
- numpy.full(shape, fill_value, dtype=None, like=None)

In [19]:
a = np.full([3,3],50)
print(a)

[[50 50 50]
 [50 50 50]
 [50 50 50]]


### linspace() method:
- Syntax:
- numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [20]:
a = np.linspace(0,20,11,dtype=int)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20]


### ndim, shape, dytpe Atrributes:

In [21]:
a = np.zeros([3,3,3],dtype=float)
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a)

3
(3, 3, 3)
float64
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


### astype() method:
- Syntax:
- ndarray.astype(dtype, order='K', casting='unsafe', subok=True, copy=True)

In [22]:
a = a.astype(np.int32)
print(a)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


### asarray() method:
- Syntax:
- numpy.asarray(a, dtype=None, order=None, *, like=None)
### nditer() method:
- Syntax:
- numpy.nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)

In [23]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
a = np.asarray(a,float,'F')
print(a)
for i in np.nditer(a):
  print(i)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
1.0
6.0
2.0
7.0
3.0
8.0
4.0
9.0
5.0
10.0


### reshape() method:
- Syntax:
- numpy.reshape(a, newshape, order='C')

In [24]:
a = np.ones([4,3],dtype=int)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


In [25]:
a = a.reshape(6,2)
print(a)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [77]:
a = np.array([9,4,6,2,7,1,5,3,8])
a= a.reshape(3,3)
print(a)

[[9 4 6]
 [2 7 1]
 [5 3 8]]


### sort() method:
- Syntax:
- ndarray.sort(axis=-1, kind=None, order=None)

In [72]:
a.sort(axis=0)
# Sorts the Coloumns
print(a)

[[2 3 1]
 [5 4 6]
 [9 7 8]]


In [74]:
a.sort(axis=1)
# Sorts the Rows
print(a)

[[4 6 9]
 [1 2 7]
 [3 5 8]]


### numpy.sort() method:
- Syntax:
- numpy.sort(a, axis=-1, kind=None, order=None)

In [76]:
a = np.sort(a,axis=0)
# Sorts the Coloumns
print(a)

[[2 3 1]
 [5 4 6]
 [9 7 8]]


In [78]:
a = np.sort(a,axis=1)
# Sorts the Rows
print(a)

[[4 6 9]
 [1 2 7]
 [3 5 8]]


### copy() method:
- Syntax:
- numpy.copy(a, order='K', subok=False)
- ndarray.copy()

In [80]:
a = np.array([1,2,3,4,5])
b = a.copy()
b = np.copy(a)
b[1] = 9
print(a)
print(b)

[1 2 3 4 5]
[1 9 3 4 5]


### concatenate() method:
- Syntax:
- numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

In [86]:
a = np.arange(0,6).reshape(2,3)
print(a)
b = np.arange(7,13).reshape(2,3)
print(b)
c = np.concatenate((a,b),axis=0) # Concatenates Rows
print(c)
d = np.concatenate((a,b),axis=1) # Concatenates Coloumns
print(d)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]


### vstack() and hstack() methods:
- Syntax:
- numpy.hstack(tup, *, dtype=None, casting='same_kind')
- numpy.vstack(tup, *, dtype=None, casting='same_kind')


In [88]:
a = np.arange(0,6).reshape(2,3)
print(a)
b = np.arange(7,13).reshape(2,3)
print(b)
c = np.hstack((a,b)) # Stack arrays in sequence horizontally
print(c)
d = np.vstack((a,b)) # Stack arrays in sequence vertically
print(d)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]
[[ 0  1  2  7  8  9]
 [ 3  4  5 10 11 12]]
[[ 0  1  2]
 [ 3  4  5]
 [ 7  8  9]
 [10 11 12]]


### where() method:
- Syntax:
- numpy.where(condition, [x, y, ]/)

In [91]:
a=np.arange(10,100,10)
print(a)
print(np.where(a==30))
print(np.where(a%30==0))

[10 20 30 40 50 60 70 80 90]
(array([2], dtype=int64),)
(array([2, 5, 8], dtype=int64),)


### add() subtract() multiply() methods

In [107]:
a=np.array([[0,1],[2,3]])
print(f"a: {a}")
print()

b=np.array([1,2])
print(f"b1: {b}")
print()

print(np.add(a,b))
print()

b=np.array([[1,2],[3,4]])
print(f"b2: {b}")
print()

print("a + b: ")
print(np.add(a,b))
print("a - b: ")
print(np.subtract(a,b))
print("a * b: ")
print(np.multiply(a,b))

a: [[0 1]
 [2 3]]

b1: [1 2]

[[1 3]
 [3 5]]

b2: [[1 2]
 [3 4]]

a + b: 
[[1 3]
 [5 7]]
a - b: 
[[-1 -1]
 [-1 -1]]
a * b: 
[[ 0  2]
 [ 6 12]]


### min() method:

In [111]:
a=np.array([[50,10,40],[30,60,20],[90,70,80]])
print(a)
print(np.min(a)) # Minimun number in the whole array
print(np.min(a,axis=0)) # Minimum number in each coloumn
print(np.min(a,axis=1)) # Minimum number in each row

[[50 10 40]
 [30 60 20]
 [90 70 80]]
10
[30 10 20]
[10 20 70]


### max() method:

In [112]:
a=np.array([[50,10,40],[30,60,20],[90,70,80]])
print(a)
print(np.max(a)) # Maximun number in the whole array
print(np.max(a,axis=0)) # Maximum number in each coloumn
print(np.max(a,axis=1)) # Maximum number in each row

[[50 10 40]
 [30 60 20]
 [90 70 80]]
90
[90 70 80]
[50 60 90]


### mean() and average() methods:

In [114]:
a=np.array([[50,10,40],[30,60,20],[90,70,80]])
print(a)
print(np.average(a))
print(np.mean(a)) # Mean of whole array
print(np.mean(a,axis=0)) # Mean of each coloumn
print(np.mean(a,axis=1)) # Mean of each row

[[50 10 40]
 [30 60 20]
 [90 70 80]]
50.0
50.0
[56.66666667 46.66666667 46.66666667]
[33.33333333 36.66666667 80.        ]


### median(), var() and std() methods:

In [116]:
a=np.array([[50,10,40],[30,60,20],[90,70,80]])
print(a)
print(np.median(a)) # Median of whole array
print(np.median(a,axis=0)) # Median of each coloumn
print(np.median(a,axis=1)) # Median of each row
print(np.var(a)) # Variance of whole array
print(np.std(a)) # Standard Deviation of whole array

[[50 10 40]
 [30 60 20]
 [90 70 80]]
50.0
[50. 60. 40.]
[40. 30. 80.]
666.6666666666666
25.81988897471611
