In [2]:
import numpy as np
a=np.array([1,2,3,4,5])
print(type(a))
print("-----------")
print(a.ndim)
print("------------")
print(np.shape(a))

<class 'numpy.ndarray'>
-----------
1
------------
(5,)


In [13]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(type(b))
print("-----------")
print(b.ndim)
print("------------")
print(np.shape(b))
b1=np.reshape(b,(5,2))
print("------------")
print(b1)

<class 'numpy.ndarray'>
-----------
2
------------
(2, 5)
------------
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [2]:
c=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(type(c))
print("-----------")
print(c.ndim)
print("------------")
print(np.shape(c))

<class 'numpy.ndarray'>
-----------
3
------------
(2, 2, 5)


In [8]:
#arrays with existing data F=column major, C-Row major order
a1=np.array([[1,2,3,4,5],[6,7,8,9,10]])
a=np.asarray(a1,float,'F')
print(a)
for i in np.nditer(a):
  print(i)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
1.0
6.0
2.0
7.0
3.0
8.0
4.0
9.0
5.0
10.0


In [12]:
#arrays with numerical ranges
n=np.arange(0,10,2)
print(n)
print("--------")
n1=np.linspace(0,20,5)
print(n1)

[0 2 4 6 8]
--------
[ 0.  5. 10. 15. 20.]


In [18]:
z=np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
o=np.ones((2,3))
o

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
f=np.full((2,3),50)
f

array([[50., 50., 50.],
       [50., 50., 50.]])

In [6]:
x=np.empty(6)
print(x)

[0. 0. 0. 0. 0. 0.]


In [43]:
x.fill(88)
print(x)

[88. 88. 88. 88. 88. 88.]


In [44]:
import numpy as np
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[1,3])
print(b[-1,-2])
print(b[1,1:4])


9
9
[7 8 9]


In [46]:
c=np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[1,2,3,4,5],[6,7,8,9,10]]])
print(c[0])
print(c[-1])
print(c[1,1,-2])
print(c[1,1,-1:-1])
print(c[0:2,0:2,0:2])
print(c[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
9
[]
[[[1 2]
  [6 7]]

 [[1 2]
  [6 7]]]
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]


In [48]:
#sort axis=0: column sort, axis=1: row sort, 

a=np.array([[6,7,8,4,5],[1,8,3,9,2]])
np.sort(a)

array([[4, 5, 6, 7, 8],
       [1, 2, 3, 8, 9]])

In [49]:

a=np.array([[6,7,8,4,5],[1,8,3,9,2]])
np.sort(a,axis=0)

array([[1, 7, 3, 4, 2],
       [6, 8, 8, 9, 5]])

In [50]:
a=np.array([[6,7,8,4,5],[1,8,3,9,2]])
np.sort(a,axis=1)

array([[4, 5, 6, 7, 8],
       [1, 2, 3, 8, 9]])

In [51]:
a=np.array([1,2,3,4,5])
c=a.copy()
c[1]=10
print(a,c)

[1 2 3 4 5] [ 1 10  3  4  5]


In [7]:
a=np.arange(0,6).reshape(2,3)
print(a)
b=np.arange(7,13).reshape(2,3)
print(b)
np.concatenate((a,b),axis=0)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
a=np.arange(0,6).reshape(2,3)
print(a)
b=np.arange(7,13).reshape(2,3)
print(b)
np.concatenate((a,b),axis=1)

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]


array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [6]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [7]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [8]:
a=np.arange(10,100,10)
print(a)
np.where(a==30)

[10 20 30 40 50 60 70 80 90]


(array([2], dtype=int64),)

In [9]:
np.where(a%30==0)

(array([2, 5, 8], dtype=int64),)

In [12]:
a=np.arange(0,4).reshape(2,2)
print(a)
b=np.array([1,2])
print(b)
np.add(a,b)

[[0 1]
 [2 3]]
[1 2]


array([[1, 3],
       [3, 5]])

In [13]:
np.subtract(a,b)

array([[-1, -1],
       [ 1,  1]])

In [16]:
np.multiply(a,a)

array([[0, 1],
       [4, 9]])

In [12]:
n=np.array([50,10,40,30,60,20,90,70,80])
a=np.reshape(n,(3,3))
print(a)

[[50 10 40]
 [30 60 20]
 [90 70 80]]


In [18]:
np.min(a)

10

In [21]:
np.min(a,axis=0)

array([30, 10, 20])

In [22]:
np.min(a,axis=1)

array([10, 20, 70])

In [13]:
print(np.max(a))
print(np.max(a,axis=1))
print(np.average(a))
print(np.mean(a))
print(np.mean(a,axis=0))
print(np.median(a))
print(np.median(a,axis=0))
print(np.var(a))
print(np.std(a))

90
[50 60 90]
50.0
50.0
[56.66666667 46.66666667 46.66666667]
50.0
[50. 60. 40.]
666.6666666666666
25.81988897471611
